#!/bin/bash

pwd
bundlebindir=`dirname $0`
bundledir=${bundlebindir/MacOS/Resources}
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home/
cd $bundledir
java -Xdock:name="FTB Launcher" -Xdock:icon="ftb.icns" -jar FTB_Launcher.jar
